### ISSUE TITLE
Another "Unable to find storage adapter ghost-storage-github"

### ISSUE THREAD

**Issue by rahendatri** [ifvictr/ghost-storage-github#44]
Hello,
I created a Ghost instance under /var/www/ghost directly on Ubuntu OS.
I tried to follow the README guide but when I restarted Ghost, I got the following error :
```
May 24 14:10:57 ubuntu node[31494]: [2021-05-24 14:10:57] INFO Ghost is running in production...
May 24 14:10:57 ubuntu node[31494]: [2021-05-24 14:10:57] INFO Your site is now available on https://ghost-myblog/
May 24 14:10:57 ubuntu node[31494]: [2021-05-24 14:10:57] INFO Ctrl+C to shut down
May 24 14:10:57 ubuntu node[31494]: [2021-05-24 14:10:57] INFO Ghost server started in 3.84s
May 24 14:10:58 ubuntu node[31494]: [2021-05-24 14:10:58] INFO Bootstrap client was closed.
May 24 14:10:59 ubuntu node[31494]: [2021-05-24 14:10:59] INFO Database is in a ready state.
May 24 14:10:59 ubuntu node[31494]: [2021-05-24 14:10:59] INFO Ghost database ready in 5.32s
May 24 14:11:10 ubuntu node[31494]: [2021-05-24 14:11:10] ERROR Unable to find storage adapter ghost-storage-github in ,/var/www/ghost/content/adapters/,/var/www/ghost/versions/4.4.0/core/server/adapters/.
May 24 14:11:10 ubuntu node[31494]:
May 24 14:11:10 ubuntu node[31494]: Unable to find storage adapter ghost-storage-github in ,/var/www/ghost/content/adapters/,/var/www/ghost/versions/4.4.0/core/server/adapters/.
May 24 14:11:10 ubuntu node[31494]: Error ID:
May 24 14:11:10 ubuntu node[31494]:     e4274890-bc99-11eb-9aff-038fa33ea23d
May 24 14:11:10 ubuntu node[31494]: ----------------------------------------
May 24 14:11:10 ubuntu node[31494]: IncorrectUsageError: Unable to find storage adapter ghost-storage-github in ,/var/www/ghost/content/adapters/,/var/www/ghost/versions/4.4.0/core/server/adapters/.
May 24 14:11:10 ubuntu node[31494]:     at new IncorrectUsageError (/var/www/ghost/versions/4.4.0/node_modules/ghost-ignition/lib/errors/index.js:98:23)
May 24 14:11:10 ubuntu node[31494]:     at AdapterManager.getAdapter (/var/www/ghost/versions/4.4.0/node_modules/@tryghost/adapter-manager/lib/AdapterManager.js:110:19)
May 24 14:11:10 ubuntu node[31494]:     at Object.getAdapter (/var/www/ghost/versions/4.4.0/core/server/services/adapter-manager/index.js:26:31)
May 24 14:11:10 ubuntu node[31494]:     at Object.getStorage (/var/www/ghost/versions/4.4.0/core/server/adapters/storage/index.js:4:27)
May 24 14:11:10 ubuntu node[31494]:     at setupSiteApp (/var/www/ghost/versions/4.4.0/core/server/web/site/app.js:112:71)
May 24 14:11:10 ubuntu node[31494]:     at setupParentApp (/var/www/ghost/versions/4.4.0/core/server/web/parent/app.js:66:44)
May 24 14:11:10 ubuntu node[31494]:     at initExpressApps (/var/www/ghost/versions/4.4.0/core/boot.js:124:57)
May 24 14:11:10 ubuntu node[31494]:     at bootGhost (/var/www/ghost/versions/4.4.0/core/boot.js:286:32)
May 24 14:11:10 ubuntu node[31494]:
May 24 14:11:10 ubuntu node[31494]: [2021-05-24 14:11:10] WARN Ghost is shutting down
May 24 14:11:10 ubuntu node[31494]: [2021-05-24 14:11:10] WARN Ghost has shut down
May 24 14:11:10 ubuntu node[31494]: [2021-05-24 14:11:10] WARN Your site is now offline
May 24 14:11:10 ubuntu node[31494]: [2021-05-24 14:11:10] WARN Ghost was running for a few seconds
May 24 14:11:10 ubuntu node[31494]: [2021-05-24 14:11:10] INFO Bootstrap client was closed.
May 24 14:11:11 ubuntu systemd[1]: Stopping Ghost systemd service for blog: ghost-myblog...
May 24 14:11:11 ubuntu node[31494]: [2021-05-24 14:11:11] WARN Ghost is shutting down
May 24 14:11:11 ubuntu node[31494]: [2021-05-24 14:11:11] WARN Ghost has shut down
May 24 14:11:11 ubuntu node[31494]: [2021-05-24 14:11:11] WARN Your site is now offline
May 24 14:11:11 ubuntu node[31494]: [2021-05-24 14:11:11] WARN Ghost was running for a few seconds
May 24 14:11:11 ubuntu node[31465]: /usr/lib/node_modules/ghost-cli/lib/process-manager.js:46
May 24 14:11:11 ubuntu node[31465]:         throw error;
May 24 14:11:11 ubuntu node[31465]:         ^
May 24 14:11:11 ubuntu node[31465]: {
May 24 14:11:11 ubuntu node[31465]:   message: 'Ghost was able to start, but errored during boot with: Unable to find storage adapter ghost-storage-github in ,/var/www/ghost/content/adapters/,/var/www/ghost/versions/4.4.0/core/server/adapters/.'
May 24 14:11:11 ubuntu node[31465]: }
May 24 14:11:11 ubuntu systemd[1]: ghost_ghost-myblog.service: Main process exited, code=exited, status=1/FAILURE
May 24 14:11:11 ubuntu systemd[1]: ghost_ghost-myblog.service: Failed with result 'exit-code'.
May 24 14:11:11 ubuntu systemd[1]: Stopped Ghost systemd service for blog: ghost-myblog.
```

However, the adapter exists under the specified folder (specified folder on README) : 
```
user@ubuntu:~/ghost/current$ tree content/adapters/
content/adapters/
├── README.md
└── storage
    └── ghost-storage-github
        ├── LICENSE.txt
        ├── README.md
        ├── build
        │   ├── index.js
        │   └── utils.js
        └── package.json
```

Plus, I tried to copy the adapter under `/var/www/ghost/content/adapters/` : 
```
user@ubuntu:~/ghost$ tree content/adapters/ -L 2
content/adapters/
├── ghost-storage-github
│   ├── LICENSE.txt
│   ├── README.md
│   ├── build
│   ├── package.json
└── storage

```

None of both solutions work and I am a bit clueless 😭 

Thanks in advance for your help.

**Comment by rahendatri** [comment]
Also discussed in https://github.com/ifvictr/ghost-storage-github/issues/37. However, the root cause is not the same since Ghost is not on Docker but directly installed on the server.
